Answer 1

In [ ]:
import numpy as np
x=np.arange(2,50,3)
print(x)

Answer 2

In [ ]:
import numpy as np
A=list(int(item) for item in input().split())
B=list(int(item) for item in input().split())
A=np.array(A)
B=np.array(B)
C=np.concatenate((A,B))
print(C)
C=np.sort(C)
print(C)




Answer 3

In [20]:
import numpy as np
#numpy array arr is given
print(arr.ndim,arr.size)

2 6


Answer 4

In [27]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr,arr.ndim,arr.shape,arr.size,sep="\t")
#using newaxis
arr1=arr[np.newaxis, :]
print(arr1,arr1.ndim,arr1.shape,arr1.size,sep="\t")
arr2=arr[:,np.newaxis]
print(arr2,arr2.ndim,arr2.shape,arr2.size,sep="\t")

[ 1  2  3  4  5  6  7  8  9 10]	1	(10,)	10
[[ 1  2  3  4  5  6  7  8  9 10]]	2	(1, 10)	10
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]	2	(10, 1)	10


In [30]:
#usind expand_dims
arr1=np.expand_dims(arr,axis=0)
print(arr1,arr1.ndim,arr1.shape,arr1.size,sep="\t")
arr2=np.expand_dims(arr,axis=1)
print(arr2,arr2.ndim,arr2.shape,arr2.size,sep="\t")

[[ 1  2  3  4  5  6  7  8  9 10]]	2	(1, 10)	10
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]	2	(10, 1)	10


Answer 5

In [41]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([[9,8,7],[6,5,4],[3,2,1]])
print(arr1)
print(arr2)
V_arr=np.vstack((arr1,arr2))
H_arr=np.hstack((arr1,arr2))
print(V_arr)
print(H_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [9 8 7]
 [6 5 4]
 [3 2 1]]
[[1 2 3 9 8 7]
 [4 5 6 6 5 4]
 [7 8 9 3 2 1]]


Answer 6

In [ ]:
import numpy as np
arr=list(int(item) for item in input().split())
unique,count = np.unique(arr, return_counts=True)
print(unique,count)